### ISSUE TITLE
Increase the productivity of the application

### ISSUE THREAD

**Issue by AI-IMED** [RafhaanShah/Simple-Notes#1]
The application will be very useful with such a beautiful interface if the following features are included:
 - Show a preview of the note details, even if a title is not included for the note, it will make finding the intended note quick instead of clicking on notes one by one
 - Import and export notes to external storage
 - swipe the note preview to the right to move the deleted note to the A recycle bin, and swipe the note preview to the left to place the note in an archive folder

**Comment by RafhaanShah** [comment]
Hi, thanks for the suggestions! 

I don't really maintain this app that much any more, but I'll definitely keep it in mind when updating it 😄
